site_name: AdaVoyager
site_url: https://wiki.adavoyager.com
repo_url: https://github.com/Wilco-OS/adavoyager
edit_uri: edit/main/docs

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  palette:
    primary:
      light: indigo
      dark: indigo
    accent:
      light: cyan
      dark: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - header.autohide
    - search.highlight
    - search.suggest

plugins:
  - search
  - obsidian-bridge

markdown_extensions:
  - toc:
      permalink: true
  - admonition