site_name: AdaVoyager
site_url: https://wiki.adavoyager.com
repo_url: https://github.com/Wilco-OS/adavoyager
edit_uri: edit/main/docs

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate    # dark-by-default
    primary:
      light: '#1A56FF'   # Royal Blue
      dark:  '#01D3DB'   # Electric Teal
    accent:
      light: '#FE00AA'   # Hot Pink
      dark:  '#6CFBCE'   # Moneta Mint
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - header.autohide
    - search.highlight
    - search.suggest

plugins:
  - search
  - obsidian-bridge

markdown_extensions:
  - toc:
      permalink: true
  - admonition